name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Change to your default branch if different
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Upload Snake to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: dist/
